### ISSUE TITLE
When will turbo-bor start to support synchronizing Polygon Mainnet data?

### ISSUE THREAD

**Issue by netquery** [maticnetwork/turbo-bor#21]
Using bor based on geth to synchronize polygon archive data will take up a lot of disk space. Erigon has a good compression effect on disk and when will turbo-bor support synchronizing mainnet data:)

**Comment by 0xKrishna** [comment]
It supports that already but is still under testing, We can't recommend this for production yet but if you want you can spin up a test node on mainnet as well.
